font_family "JetBrains Mono"
font_size 18.0
bold_font "JetBrains Mono Bold"
italic_font "JetBrains Mono Italic"

cursor_blink_interval -1
mouse_hide_wait 2.0
hide_window_decorations yes
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
copy_on_select yes
startup_session launch.conf
confirm_os_window_close 0
cursor_trail 3
cursor_trail_decay 0.1 0.4
background_opacity 0.9


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
