WHEEL_UP      seek 10                  # seek 10 seconds forward
WHEEL_DOWN    seek -10                 # seek 10 seconds backward
WHEEL_LEFT    add volume -2
WHEEL_RIGHT   add volume 2

UP    add volume 2
DOWN  add volume -2
RIGHT seek  10
LEFT  seek -10

I show-text "${filename}"              # display filename in osd

L cycle-values loop-playlist "inf" "no"

 cycle framedrop

ENTER playlist-next force

ESC quit

+ add audio-delay 0.100
- add audio-delay -0.100
F cycle sub-forced-events-only
